ntrip_server: aristosrobot.com:2101
ntrip_user: test
ntrip_pass: test
ntrip_stream: IKH_CHIRIQUI_RTCM32 #IKH_CHIRIQUI_RTCM32 # IKH_DOMOKOS_RTCM32 #IKH_CHIRIQUI_RTCM32
nmea_gga: $GPGGA,%02d%02d%04.2f,0823.309,N,08219.450,W,1,12,1.0,0.0,M,0.0,M,,*7E
